//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryType3Email
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASAQEmail
    {
        public int EmailID { get; set; }
        public string Importer { get; set; }
        public string BondNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
    }
}
