//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryType3Email
{
    using System;
    using System.Collections.Generic;
    
    public partial class BO_Record
    {
        public string surety_code { get; set; }
        public string rdp { get; set; }
        public string bond_number { get; set; }
        public string bond_activity_code { get; set; }
        public Nullable<System.DateTime> bond_effective_date { get; set; }
        public Nullable<System.DateTime> bond_termination_date { get; set; }
        public Nullable<float> bond_liability_amount { get; set; }
        public Nullable<System.DateTime> reconciliation_rider_effective_date { get; set; }
        public string filler1 { get; set; }
        public string importer_number_line_1 { get; set; }
        public string importer_name { get; set; }
        public string importer_address { get; set; }
        public string filler2 { get; set; }
        public string importer_address_line_2 { get; set; }
        public string importer_city { get; set; }
        public string importer_state { get; set; }
        public string importer_5digit_zip { get; set; }
        public string importer_4digit_zip { get; set; }
        public string filler3 { get; set; }
        public System.DateTime file_date { get; set; }
    }
}
