//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryType3Email
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cbpmqdbEntities1 : DbContext
    {
        public cbpmqdbEntities1()
            : base("name=cbpmqdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASAQEmail> ASAQEmails { get; set; }
        public virtual DbSet<BondType> BondTypes { get; set; }
        public virtual DbSet<ClassCode> ClassCodes { get; set; }
        public virtual DbSet<EntryType> EntryTypes { get; set; }
        public virtual DbSet<FilerCode> FilerCodes { get; set; }
        public virtual DbSet<AQ_Record> AQ_Record { get; set; }
        public virtual DbSet<AS_Record> AS_Record { get; set; }
        public virtual DbSet<BO_Record> BO_Record { get; set; }
        public virtual DbSet<PortCode> PortCodes { get; set; }
        public virtual DbSet<vType3EntriesWithBO> vType3EntriesWithBO { get; set; }
    
        public virtual ObjectResult<spGetType3Entries_Result> spGetType3Entries(Nullable<System.DateTime> fromDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetType3Entries_Result>("spGetType3Entries", fromDateParameter);
        }
    }
}
