//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryType3Email
{
    using System;
    using System.Collections.Generic;
    
    public partial class vType3EntriesWithBO
    {
        public Nullable<decimal> district_port_of_entry1 { get; set; }
        public string filer_code1 { get; set; }
        public string entry_number1 { get; set; }
        public string surety_code { get; set; }
        public string bond_number { get; set; }
        public Nullable<byte> bond_type { get; set; }
        public Nullable<byte> entry_type { get; set; }
        public Nullable<byte> release_summary_indicator { get; set; }
        public string importer_of_record { get; set; }
        public Nullable<byte> entry_source { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<decimal> value { get; set; }
        public string broker_reference_number { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<byte> collection_status { get; set; }
        public Nullable<decimal> district_port_of_entry2 { get; set; }
        public string filer_code2 { get; set; }
        public string entry_number2 { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<byte> record_status { get; set; }
        public string accelerated_drawback_indicator { get; set; }
        public Nullable<byte> possible_late_indicator { get; set; }
        public string oga_indicator { get; set; }
        public Nullable<System.DateTime> entry_summary_date { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
        public string warehouse_entry_summary_number { get; set; }
        public Nullable<System.DateTime> tentative_tib_close_date_liquidation_date { get; set; }
        public Nullable<decimal> estimated_duty { get; set; }
        public Nullable<decimal> estimated_taxes { get; set; }
        public Nullable<decimal> district_port_of_entry3 { get; set; }
        public string filer_code3 { get; set; }
        public string entry_number3 { get; set; }
        public Nullable<decimal> estimated_fee { get; set; }
        public Nullable<decimal> estimated_antidumping_duty { get; set; }
        public Nullable<decimal> bonded_antidumping_duty { get; set; }
        public Nullable<decimal> estimated_countervailing_duty { get; set; }
        public Nullable<decimal> bonded_countervailing_duty { get; set; }
        public string recon_entry_nafta_issue_entry_type_09 { get; set; }
        public string recon_entry_other_issue_entry_type_09 { get; set; }
        public Nullable<byte> pay_basis_indicator { get; set; }
        public string filler3 { get; set; }
        public Nullable<decimal> district_port_of_entry4 { get; set; }
        public string filer_code4 { get; set; }
        public string entry_number4 { get; set; }
        public string nafta_reconciliation_flag { get; set; }
        public string nafta_reconciliation { get; set; }
        public string other_reconciliation_flag { get; set; }
        public string other_reconciliation_entry { get; set; }
        public string single_entry_bond_amount { get; set; }
        public string single_entry_bond_producer_account_number { get; set; }
        public string filler4 { get; set; }
        public Nullable<decimal> district_port_of_entry5 { get; set; }
        public string filer_code5 { get; set; }
        public string entry_number5 { get; set; }
        public string first_associated_import_entry { get; set; }
        public string next_associated_import_entry_1 { get; set; }
        public string next_associated_import_entry_2 { get; set; }
        public string next_associated_import_entry_3 { get; set; }
        public string next_associated_import_entry_4 { get; set; }
        public string filler5 { get; set; }
        public System.DateTime file_date { get; set; }
        public string importer_name { get; set; }
        public Nullable<System.DateTime> bond_effective_date { get; set; }
        public Nullable<System.DateTime> bond_termination_date { get; set; }
        public Nullable<float> bond_liability_amount { get; set; }
        public string importer_city { get; set; }
        public string importer_state { get; set; }
        public string importer_5digit_zip { get; set; }
        public string importer_4digit_zip { get; set; }
        public string rdp { get; set; }
        public string bond_activity_code { get; set; }
        public Nullable<byte> Expr1 { get; set; }
        public System.DateTime Expr2 { get; set; }
    }
}
